### ISSUE TITLE
Add ability to keep preset groups sorted in the menu

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks-issues#1]
Presets model and group model (see `presetsGroups.getGroupModel()`) in the context menu (menu `presetsMenu` in files `ArtworkEditView.qml` **and others**) is a `QSortFilterProxyModel`. Need to override `bool lessThan(int, int)` method and if a Setting (we should add new setting in class `SettingsModel`) to keep presets sorted is ON, then sort preset groups (see example with `FilteredArtworksListModel::lessThan()`) by name

Implementation is trivial, hard part is to find a correct place.

Example of presets from context menu: https://xpiksapp.com/tutorials/presets-groups/

Xpiks docs on how to add a new setting: https://github.com/ribtoks/xpiks/blob/master/docs/How-to-add-a-new-Setting-to-Xpiks.md (private repo)

**Comment by xaizek** [comment]
Need clarification. Do I get it right that list of presets should be sorted and not list of preset groups (I thought maybe both of them)? The text is somewhat ambiguous and I don't see `QSortFilterProxyModel` being used for groups of presets.

**Comment by ribtoks** [comment]
@xaizek List of groups should be sorted too. In file `presetgroupsmodel.h` add new class `FilteredPresetGroupsModel` and copy-paste implementation from `FilteredPresetKeywordsModel`. Just instead of overriding `filterAcceptsRow()` you will override `lessThan()`. This new class should take `SettingsModel` and `PresetGroupsModel` references in constructor and it should be a top-level class parented in `XpiksApp`. From `SettingsModel` it will get your new setting for keeping presets sorted. You can see how to implement `lessThan()` with similar setup in `FilteredArtworksListModel::lessThan()`
