### ISSUE TITLE
Size restoration improvements

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks-issues#15]
When Xpiks size is changed, it is memorized in settings and restored on the next launch.

This is not finished in a sense of full-screen expansion. When Xpiks is expanded to full-screen it remembers it's size and when closed and reopened, it switches to the previous size which might not be correct due to a number of reasons (user changed monitors etc.).

What should be done: in addition to size, save also state (normal, maximized, minimized etc.) and apply it same way as size is applied.

Xpiks docs about saving state: https://github.com/ribtoks/xpiks/blob/master/docs/How-to-save-a-state-of-an-entity.md (private repo)

**Comment by IlyaEfimoff** [comment]
i will do this task
