### ISSUE TITLE
Paste context menu in Keywords field

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks-issues#17]
There's a submenu with item "Insert preset" (look for `presetsMenu` in the `MainGrid.qml`, `ArtworkEditView.qml` and `CombinedEditView.qml`). Add menu item "Paste" with pasting from the clipboard (if any content) in ALL keyword editing fields (presets, main view, single editing, combined editing, user dictionary). There are multiple examples how to paste from clipboard in any of `MainGrid.qml`, `ArtworkEditView.qml`, `CombinedEditView.qml`.

How the keywords field looks like: https://xpiksapp.com/tutorials/keywords-overview/

**Comment by IlyaEfimoff** [comment]
For this task, there are still improvements?

**Comment by ribtoks** [comment]
No, it is closed. I forgot to sync with main issue tracker.
