### ISSUE TITLE
Xpiks Not Supoort PNG File

### ISSUE THREAD

**Issue by arrysoeryono** [ribtoks/xpiks-issues#25]
Dear Xpiks Developer,
Please help for support Xpiks for PNG file. Thank you. Ari Suryono

https://user-images.githubusercontent.com/72296427/125651924-f0944564-5af8-4bde-ad1f-69a757f82dc3.mp4

**Comment by ribtoks** [comment]
This is implemented as of Xpiks 1.7.0.4
