### ISSUE TITLE
Show full file title in Failed uploads

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks-issues#3]
Currently it is impossible to understand which file exactly has failed to upload because filenames are shortened. This task is about adding a Tooltip for each item that will show full filename in file `FailedUploadArtworks.qml`.

![65376377-d70f2100-dc53-11e9-89e9-d21e7919f5b7](https://user-images.githubusercontent.com/505555/81674438-d5e66a80-9455-11ea-8b62-6d18669a0d49.png)

Example of such tooltip usage: check usage of `StyledTooltip` in qml files.

In order to get failed uploads need to upload few photos to some invalid ftp address or valid address with networking turned off. All uploads will go to `FailedUploadArtworks.qml`.

How to upload files: https://xpiksapp.com/tutorials/intro-uploading/

**Comment by IlyaEfimoff** [comment]
i will do this task
