### ISSUE TITLE
Warning for vector preview size

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks-issues#5]
There're multiple warnings being already detected inside `WarningsItem::checkWarnings()` API. Need to add another check in case artwork is a vector: verify that vector preview more or equal than a value from setting of class `WarningsSettingsModel`

Set this new warning setting to default at 15 MP (Adobe Stock requirement)

There's a twin issue #10

**Comment by IlyaEfimoff** [comment]
How can I add a preview vector?

**Comment by taras-clarifai** [comment]
> How can I add a preview vector?

Vector preview is a `.jpg` file with the same name as vector (e.g. `file.jpg` and `file.eps`). You can add existing vectors in Xpiks repository `src/xpiks-tests/images-for-tests/vector`

**Comment by ribtoks** [comment]
> How can I add a preview vector?

Vector preview is a `.jpg` file with the same name as vector (e.g. `file.jpg` and `file.eps`). You can add existing vectors in Xpiks repository `src/xpiks-tests/images-for-tests/vector`

**Comment by IlyaEfimoff** [comment]
add parameter MIN_VECTOR_PREVIEV_MEGAPIXELS in "https://api.xpiksapp.com/dev/warnings-settings"

Warnings::WarningsSettingsModel::parseConfig - MIN_VECTOR_PREVIEV_MEGAPIXELS value is not number

**Comment by ribtoks** [comment]
I updated json. Here's how it looks now:

```
{
    "overwrite": false,
    "version": 1,

    "settings": {
        "additional_allowed_chars": "._-@#",
        "max_description_length": 200,
        "min_keywords_count": 7,
        "max_keywords_count": 50,
        "min_megapixels": 4.0,
        "min_words_count": 3,
        "max_image_filesize_mb": 25.0,
        "max_video_filesize_mb": 4096.0,
        "max_vector_filesize_mb": 50.0,
        "max_video_duration_s": 60.0,
        "min_video_duration_s": 5.0,
        "min_vector_preview_megapixels": 15.0
    }
}
```

**Comment by ribtoks** [comment]
New properties: `max_vector_filesize_mb` and `min_vector_preview_megapixels`

**Comment by IlyaEfimoff** [comment]
Warnings::WarningsSettingsModel::parseConfig - MIN_VECTOR_PREVIEV_MEGAPIXELS value is not number

FIXED

**Comment by IlyaEfimoff** [comment]
For this task, there are still improvements?

**Comment by ribtoks** [comment]
Please check PR comments
