### ISSUE TITLE
Video thumbnails are not shown in Failed uploads window

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks-issues#6]
This task is only about investigation. There should a be a separate task for the fix.

For some reason video thumbnails don't always show up on Failed uploads window

![65376377-d70f2100-dc53-11e9-89e9-d21e7919f5b7](https://user-images.githubusercontent.com/505555/81674619-278ef500-9456-11ea-9bca-2ea3d3154400.png)

Need to investigate. Result of this task is either a fix (if it's easy) or investigation results what went wrong and how to fix it.

In order to investigate need to upload few videos to some invalid ftp address or valid address with networking turned off. All uploads will go to `FailedUploadArtworks.qml`. Need to check from there what is up with the videos.

How to upload files: https://xpiksapp.com/tutorials/intro-uploading/

**Comment by IlyaEfimoff** [comment]
This method always returns false.

bool ThumbnailCreator::createThumbnail(std::vector<uint8_t> &rgbBuffer, int &width, int &height) {
        (void)rgbBuffer;
        width = 0;
        height = 0;
        return false;
    }

**Comment by ribtoks** [comment]
This is not a real `xpks` lib. See if you can reproduce the issue using original Xpiks: https://xpiksapp.com/downloads/
If you can, then we can work on this issue.

**Comment by IlyaEfimoff** [comment]
I installed the application and reproduced the problem.

**Comment by ribtoks** [comment]
Great! That means we can investigate why it is not set. 

In method `ThumbnailCreator::createThumbnail()` you can generate a buffer of size 90000 elements (to simulate image 300x300 pixels). Set each element of the array to `0xff0000` (format is `Format_RGB888` that is RGB where each component has 1 byte) which will generate you red rectangles.

After this just rebuild vendors (libxpks is part of vendors) and you can try to investigate the root cause of the issue! See where thumbnails on `FailedUploads` are coming from.

**Comment by ribtoks** [comment]
@IlyaEfimoff Thumbnails for display is coming from `UploadWatcher::data()` method. We need to check why it does not have a valid picture for video.

**Comment by IlyaEfimoff** [comment]
After a quick analysis, it became clear that the wrong file path was being set in FailedUploadArtworks.qml. 

source: "image://cached/" + helpersWrapper.toImagePath(imageItem.delegateData)
Here is the path to the video file, not the thumbnail.

I'll try to find out the reason.
